version: "3.7"

services:
  pydocker:
    build: .
    command: python3 myWebApp.py # Prevents container from exiting
    restart: always
    ports:
      - "127.0.0.1:3127:3127"
    volumes:
      - ./:/app
